"""Add unique constraint to employee_roles

Revision ID: 42787051bec1
Revises: 2b57179231ac
Create Date: 2024-11-15 19:19:43.173708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42787051bec1'
down_revision: Union[str, None] = '2b57179231ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_employee_role', 'employee_roles', ['employee_id', 'role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_employee_role', 'employee_roles', type_='unique')
    # ### end Alembic commands ###
